export const allTodos = [
  {
    id: 1,
    uid: 1,
    title: 'Купить вкусный кофе',
    description: 'Сходить в соседнюю кофейню и взять вкусного моккачино',
    assignDate: '21/06/2019',
    fromDate: '22/06/2021',
    toDate: '23/06/2021',
    boundTasks: [
      {
        from: 'Цыпа Петр Семенович',
        taskId: 2,
        taskTitle: 'Комментарий пользователя к задаче переносится на новую строку',
        status: 'agreed',
      },
    ],
    from_uid: 3,
    status: 'new',
  },
  {
    id: 2,
    uid: 1,
    title: 'Посмотреть новый фильм Квентина Тарантино',
    description: 'Вышел новый фильм Квентина Тарантино, поэтому стоит купить билеты и сходить в кино в ближайшее время',
    assignDate: '21/06/2019',
    fromDate: '22/06/2021',
    toDate: '23/06/2021',
    boundTasks: [
      {
        from: 'Цыпа Петр Семенович',
        taskId: 2,
        taskTitle: 'Комментарий пользователя к задаче переносится на новую строку',
        status: 'agreed',
      },
    ],
    from_uid: 4,
    status: 'inProgress',
  },
  {
    id: 3,
    uid: 1,
    title: 'Купить новый пуховик',
    description: 'На улице холодно, поэтому стоит прикупить новый пуховик, чтобы не мерзнуть',
    assignDate: '21/06/2019',
    fromDate: '22/06/2021',
    toDate: '23/06/2021',
    boundTasks: [
      {
        from: 'Цыпа Петр Семенович',
        taskId: 3,
        taskTitle: 'Комментарий пользователя к задаче переносится на новую строку',
        status: 'agreed',
      },
      {
        from: 'Цыпа Александр Семенович',
        taskId: 4,
        taskTitle: 'Да хватит уже комментарии переносить на новые строки',
        status: 'agreed',
      },
    ],
    from_uid: 5,
    status: 'delayed',
  },
];